Repository DecodersCommunity/calculator, pull requests merged in 2022-10, with the labels that each got.

#3 Basic Calculator App
  src/index.html
  src/script.js
  src/style.css
Labels: good first issue, hacktoberfest-accepted

#6 Added padding from left in input field
  src/style.css
Labels: good first issue, hacktoberfest-accepted

#9 input section of calculator was not set properly so i changes some cs…
  src/style.css
Labels: good first issue, hacktoberfest-accepted

#10 Calculator UI Enhanced
  src/index.html
  src/style.css
Labels: hacktoberfest-accepted

#18 validation, autofocus & keyevents added
  src/index.html
  src/script.js
Labels: enhancement, hacktoberfest-accepted

#12 Some styling
  src/index.html
  src/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#21 Added favicon
  assets/favicon.ico
  src/index.html
Labels: enhancement, hacktoberfest-accepted

#26 Added Calculator Functionality i.e., error handling for invalid input
  src/script.js
Labels: hacktoberfest-accepted

#27 adding mute_unmute button
  src/index.html
  src/script.js
Labels: enhancement, hacktoberfest-accepted

#32 Update style.css
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#33 Update style.css
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#28 Introduced Backspace
  src/index.html
  src/script.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added some style to the button and fix -positions of letter
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#30 Add history section
  src/index.html
  src/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#36 Make changes in shadow of the calculator
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted
